app/models/word.py
from json import loads

from app import db


class Word(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    word = db.Column(db.String(100), nullable=False, unique=True)
    definitions = db.Column(db.JSON, nullable=False)
    power = db.Column(db.Integer, nullable=False, default=1)

app/forms/word.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    word = StringField('Word', validators=[DataRequired()], render_kw={'placeholder': 'Enter The Word'})
    submit = SubmitField('Search')

app/routes/word.py
from flask import Blueprint, render_template, flash, jsonify
from flask_login import login_required, current_user

from app import db
from app.models.word import Word
from app.forms.word import SearchForm
from app.services.api import ApiService

word = Blueprint('word', __name__, url_prefix='/word')


@word.route('/')
@word.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form, model = SearchForm(), False

    if form.validate_on_submit():
        api = ApiService()
        response = api.translate(form.word.data)

        if response['success']:
            model = response['model']
        else:
            flash(response['message'], 'danger')

    return render_template('views/word/index.html', title='Search Word', form=form, model=model)


@word.route('/<int:id>/add')
@login_required
def add_word(id):
    word = Word.query.filter_by(id=id).first_or_404()
    current_user.dictionary.append(word)
    db.session.commit()
    return 'ok'


@word.route('/<int:id>/remove')
@login_required
def remove_word(id):
    word = Word.query.filter_by(id=id).first_or_404()
    current_user.dictionary.remove(word)
    db.session.commit()
    return 'ok'


@word.route('/my_words')
@login_required
def my_words():
    words = current_user.dictionary.all()
    return render_template('views/word/my_words.html', title='My Words', words=words)

app/templates/views/word/index.html
{% extends 'assets/base.html' %}

{% block content %}
    <h1 class="mt-5">{{ title }}</h1>
    <div class="row">
        <div class="col-md-12">
            {{ error(form) }}
            {{ alert() }}
        </div>
    </div>
    <form method="POST" , action="">
        {{ form.hidden_tag() }}
        <div class="row">
            <div class="col-md-11">
                <div class="form-group">

                    {{ form.word(class='form-control') }}
                </div>
            </div>
            <div class="col-md-1">
                {{ form.submit(class='btn btn-primary') }}
            </div>
        </div>
    </form>
    {% if model %}
        <hr>
        <div class="row">
            <div class="col-md-10">
                <h2>Word: {{ model.word }}</h2>
            </div>
            <div class="col-md-2">
                <td>
                    <button type="button" onclick='add_word("{{ url_for('word.add_word', id=model.id) }}")' class="btn btn-primary">Add My Dictionary</button>
                </td>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-borderless">
                    <thead>
                    <tr>
                        <th scope="col" width="15%">Type</th>
                        <th scope="col" width="85%">Definition</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for definition in model.definitions %}
                        <tr>
                            <td>
                                {{ definition['partOfSpeech'] }}
                            </td>
                            <td>
                                {{ definition['definition'] }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block js %}
    <script>
        function add_word(url){
            $.get(url,
              function (data, textStatus, jqXHR) {
                 alert('Added');

                 if (data.includes('Success')){
                     window.location.href = "http://www.w3schools.com";
                 }
            });
        }
    </script>
    <script
          src="https://code.jquery.com/jquery-3.5.1.min.js"
          integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
          crossorigin="anonymous">
    </script>
{% endblock %}

app/templates/views/word/my_words.html
{% extends 'assets/base.html' %}

{% block content %}
    <h1 class="mt-5">{{ title }}</h1>
    <table class="table">
        <tbody>
            {% for word in words %}
                <div id="{{ word.id }}">
                    <tr>
                        <th colspan="3">
                            Word: {{ word.word }}
                        </th>
                    </tr>
                    <tr>
                        <td>
                            {% for definition in word.definitions %}
                                - {{ definition['definition'] }} <br>
                            {% endfor %}
                        </td>
                    </tr>
                </div>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}