app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user

from app import db
from app.models.user import User
from app.forms.auth import LoginForm, RegisterForm

auth = Blueprint('auth', __name__, url_prefix='/auth')


@auth.route('/')
@auth.route('/index')
def index():
    return 'ok'


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash('Login Failed', 'danger')
        else:
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('main.index'))

    return render_template('views/auth/login.html', title='User Login', form=form)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(email=form.email.data, first_name=form.first_name.data, last_name=form.last_name.data)
        user.generate_password_hash(form.password.data)

        db.session.add(user)
        db.session.commit()

        flash('Registered Successfully, Please Login', 'success')

    return render_template('views/auth/register.html', title='User Register', form=form)


@auth.route('/logout')
def logout():
    logout_user()
    flash('Logout Successfully', 'success')
    return redirect(url_for('auth.login'))

app/routes/main.py
from flask import Blueprint, render_template, jsonify
from flask_login import login_required

from app.services.api import ApiService

main = Blueprint('main', __name__, url_prefix='/')


@main.route('/')
@main.route('/index')
@login_required
def index():
    return render_template('views/main/index.html', title='Home')


@main.route('/about')
def about():
    return render_template('views/main/about.html', title='About')


@main.route('/test/<string:value>')
def test(value):
    api = ApiService()
    word = api.translate(value)

    if word['success']:
        return jsonify(word['model'].definitions)

    return jsonify(word)

app/routes/word.py
from flask import Blueprint, render_template, flash, jsonify
from flask_login import login_required, current_user

from app import db
from app.models.word import Word
from app.forms.word import SearchForm
from app.services.api import ApiService

word = Blueprint('word', __name__, url_prefix='/word')


@word.route('/')
@word.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form, model = SearchForm(), False

    if form.validate_on_submit():
        api = ApiService()
        response = api.translate(form.word.data)

        if response['success']:
            model = response['model']
        else:
            flash(response['message'], 'danger')

    return render_template('views/word/index.html', title='Search Word', form=form, model=model)


@word.route('/<int:id>/add')
@login_required
def add_word(id):
    word = Word.query.filter_by(id=id).first_or_404()
    current_user.dictionary.append(word)
    db.session.commit()
    return 'ok'


@word.route('/<int:id>/remove')
@login_required
def remove_word(id):
    word = Word.query.filter_by(id=id).first_or_404()
    current_user.dictionary.remove(word)
    db.session.commit()
    return 'ok'


@word.route('/my_words')
@login_required
def my_words():
    words = current_user.dictionary.all()
    return render_template('views/word/my_words.html', title='My Words', words=words)

app/templates/assets/base.html
{% from "macros/alerts.html" import error, alert %}

<!doctype html>
<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Personal Dictionary and Word Memorizing APP">
    <meta name="author" content="Yunus Emre Geldegül">

    <title>
        {% if title %}
            {{ title }} - Garfield
        {% else %}
            Garfield
        {% endif %}
    </title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/">
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/sticky-footer-navbar.css" rel="stylesheet">

    {% block css %}

    {% endblock %}
</head>
<body>
{% include 'assets/header.html' %}

<main role="main" class="container">
    {% block content %}
        <h1 class="mt-5">Header</h1>
        <p class="lead">Content</p>
        <p>Sub Content</p>
    {% endblock %}
</main>

{% include 'assets/footer.html' %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>
    window.jQuery || document.write(
        '<script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/jquery-slim.min.js"><\/script>'
    )
</script>
<script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
<script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>

{% block js %}

{% endblock %}
</body>
</html>

app/templates/assets/footer.html
<footer class="footer">
    <div class="container">
        <span class="text-muted">Personal Dictionary and Word Memorizing APP</span>
    </div>
</footer>

app/templates/assets/header.html
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Garfield</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link disabled" href="">
                            {{ current_user.first_name }} {{ current_user.last_name }}
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('word.index') }}">Search Words</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('word.my_words') }}">My Words</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('quiz.index') }}">Quiz</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>