app/models/quiz.py
from app import db


class Quiz(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    user = db.relationship('User', backref='user')
    point = db.Column(db.Integer, nullable=False)
    created_at = db.Column(db.DateTime, default=db.func.now(), nullable=False)

app/routes/quiz.py
from random import shuffle
from flask import Blueprint, render_template, flash, session, redirect, url_for, request
from flask_login import login_required, current_user
from sqlalchemy.sql.expression import func

from app import db
from app.models.word import Word
from app.models.quiz import Quiz

quiz = Blueprint('quiz', __name__, url_prefix='/quiz')


@quiz.route('/')
@quiz.route('/index')
@login_required
def index():
    session['quiz_words'] = [word.word for word in current_user.dictionary.order_by(func.random()).limit(10).all()]
    session['quiz_point'] = 0

    exams = Quiz.query.filter_by(user=current_user).order_by(Quiz.created_at.desc()).all()
    session['start'] = False

    if len(session['quiz_words']) > 10:
        session['start'] = True

    return render_template('views/quiz/index.html', title="Quiz", exams=exams)


@quiz.route('/question')
@login_required
def question():
    if len(session['quiz_words']) == 0:
        return redirect(url_for('quiz.finish'))

    if not session['start']:
        flash('Not Enough Words To Start The Exam!', 'danger')
        return redirect(url_for('quiz.index'))

    session['quiz_word'] = session['quiz_words'].pop()
    word = Word.query.filter_by(word=session['quiz_word']).first()
    definition_one = word.definitions[0]
    definition_two = Word.query.filter(Word.word != word.word).order_by(func.random()).limit(1).first()
    definition_three = Word.query.filter(Word.word != word.word).filter(Word.word != definition_two.word).order_by(
        func.random()).limit(1).first()
    mix = [definition_three.definitions[0], definition_two.definitions[0], definition_one]

    shuffle(mix)

    return render_template('views/quiz/question.html', title='Question', word=session['quiz_word'], mix=mix)


@quiz.route('/answer', methods=['POST'])
@login_required
def answer():
    word = request.form.get('word')
    wote = request.form.get('wote')

    word = Word.query.filter_by(word=word).first()

    for i in word.definitions:
        if wote == i['definition']:
            session['quiz_point'] += 1
            return 'Success! 1 Point Added'

    session['quiz_point'] -= 2
    return 'Failed! 1 Points Deleted'


@quiz.route('/finish')
@login_required
def finish():
    point = session['quiz_point']

    quiz_model = Quiz()
    quiz_model.point = point
    quiz_model.user = current_user

    db.session.add(quiz_model)
    db.session.commit()

    flash('Quiz Finished! Point: {}'.format(point), 'success')

    session.pop('quiz_point')

    return redirect(url_for('quiz.index'))

app/templates/views/quiz/index.html
{% extends 'assets/base.html' %}

{% block content %}
    <h1 class="mt-5">{{ title }}</h1>

    {% if session['start'] %}
        <hr>
            <a href="{{ url_for('quiz.question') }}">Start A  Quiz</a>
        <hr>
    {% else %}
        <hr>
            To start the course you need to load at least 10 words.
        <hr>
    {% endif %}

    {{ alert() }}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Date</th>
            <th scope="col">Point</th>
        </tr>
        </thead>
        <tbody>
        {% for exam in exams %}
            <tr>
                <td>{{ exam.id }}</td>
                <td>{{ exam.created_at }}</td>
                <td>{{ exam.point }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
{% endblock %}

app/templates/views/quiz/question.html
{% extends 'assets/base.html' %}

{% block content %}
    <h1 class="mt-5">{{ title }}</h1>
    <p>Word: {{ word }}</p><br>
    <p>
        <button type="button" class="btn btn-secondary"
                onclick="add_wote('{{ word }}', '{{ mix[0]['definition'] }}');">{{ mix[0]['definition'] }}</button>
    </p>
    <p>
        <button type="button" class="btn btn-secondary"
                onclick="add_wote('{{ word }}', '{{ mix[1]['definition'] }}');">{{ mix[1]['definition'] }}</button>
    </p>
    <p>
        <button type="button" class="btn btn-secondary"
                onclick="add_wote('{{ word }}', '{{ mix[2]['definition'] }}');">{{ mix[2]['definition'] }}</button>
    </p>
{% endblock %}

{% block js %}
    <script>
        function add_wote(word, wote) {
            var url = '{{ url_for('quiz.answer') }}';
            $.ajax({
                url: url,
                type: "POST",
                data: {word: word, wote: wote},
                success: function (data) {
                    alert(data);
                    window.location.replace("{{ url_for('quiz.question') }}");
                }
            });
        }
    </script>
    <script
            src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous">
    </script>
{% endblock %}